name: Deploy do projeto em S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Dependências e Construir o Projeto
        run: |
          npm install
          npm run build --prod

      - name: Deploy para AWS S3
        run: |
          aws s3 sync ./dist/ s3://lp-psi-kelly --delete --acl public-read
